name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  http: ^1.2.1
  shelf_router: ^1.1.4
  postgres: ^2.6.4
  intl: ^0.20.2                 # Updated from ^0.19.0
  flutter_secure_storage: ^9.0.0
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.2.0     # Updated from ^2.3.2
  shelf_multipart: ^2.0.1       # Updated from ^2.0.0
  shelf_static: ^1.1.3          # Updated from ^1.0.0

dev_dependencies:
  lints: ^6.0.0              # Updated from ^5.1.1
  test: ^1.26.3
